version: '3.8'

services:
  eve_server:
    container_name: eve_server
    build: /src
    restart: always
    ports:
      - 9741:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - PYTHONUNBUFFERED=1
    depends_on:
      - eve_db
    command: python main.py --env prod

  eve_db:
    container_name: eve_db
    image: postgres:16.4
    restart: always
    user: root
    ports:
      - 9742:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  eve_ui:
    container_name: eve_ui
    build: my-app
    restart: always
    ports:
      - 9743:80
    depends_on:
      - eve_server

volumes:
  pgdata:
