FROM node:12-alpine as builder
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
RUN npm i web-vitals --save-dev
COPY . /app
RUN npm run build
FROM nginx:1.19-alpine
COPY --from=0 /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]