from src.storage.repositories.base import BaseRepository
from src.storage.repositories.order_repository import OrderRepository
from src.storage.repositories.product_repository import ProductRepository
from src.storage.repositories.transacion_repository import TransactionRepository
from src.storage.repositories.type_info_repository import TypeInfoRepository
from src.storage.repositories.material_repository import MaterialRepository
